# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/mim1/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    zsh-syntax-highlighting
    sudo
    web-search
    copypath
    copyfile
    copybuffer
    jsontools
    zsh-autosuggestions
    kubectx
    helm
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# usr aliases
alias v="vim"
alias r="ranger"
alias s="grep -HiIrne"
alias n="netstat -tulpn"
alias i3lck="i3lock -c 000000"
alias lck="sl && i3lck"
alias öö="ll | lolcat"
alias ää="ll | lolcat"
alias üü="ll | lolcat"
alias chrome="google-chrome"

# network stuff
alias won="nmcli radio wifi on"
alias woff="nmcli radio wifi off"
alias nmrestart="sudo systemctl restart network-manager"

# kubectl stuff
alias k="kubectl"
alias kapf="kubectl apply -f"
alias kdef="kubectl delete -f"
alias ctx="kubectl config get-contexts"
alias ctxc="kubectl config use-context"

# kubectx plugin stuff
RPS1='$(kubectx_prompt_info)'

#kubectx_mapping[context_name_from_kubeconfig]="$emoji[wolf_face]"
kubectx_mapping[ai-cluster-v2]="%{$fg[yellow]%}ai-cluster-v2%{$reset_color%}"
kubectx_mapping[minikube]="%{$fg[red]%}minikube%{$reset_color%}"


# enable kubectl autocompletion in zsh
source <(kubectl completion zsh)
complete -F __start_kubectl k

# function to adjust brightness for laptop/monitor screen
function br() {xrandr --output eDP-1-1 --brightness 0."$1";}

# function to adjust brightness for laptop screen
function lbr() {xrandr --output eDP-1 --brightness 0."$1";}

# function to pprint csv
function pretty_csv {
    column -t -s, -n "$@" | less -F -S -X -K
}

# function to pprint tsv
function pretty_tsv {
    column -t -s $'\t' -n "$@" | less -F -S -X -K
}

# setup dual monitors @home
alias dm="source .screenlayout/home_setup.sh"
alias sm="source .screenlayout/laptop_setup.sh"

# virtualenv for python
alias venv="virtualenv venv"
alias activate="source venv/bin/activate"

# folder stuff
alias cdpdev="cd ~/github"

# rc stuff
alias bashrc="vim ~/.bashrc"
alias bashrcreload="source ~/.bashrc"
alias zshrc="vim ~/.zshrc"
alias zshrcreload="source ~/.zshrc"
alias vimrc="vim ~/.vimrc"
alias vimrcreload="source ~/.vimrc"
alias i3rc="vim ~/.config/i3/config"

# fzf stuff
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# keyboard layout
alias mgus="setxkbmap -layout us -variant altgr-intl"
alias mger="setxkbmap -layout de"

# fix for glcoud/gsutil ffi.h error
export CLOUDSDK_PYTHON="python3.8"

# ls list dirs first, and afterwards other files
alias ls='ls --color -h --group-directories-first'
